{
 "title": "Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"indoor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"outdoor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "measurement": "humidity",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"indoor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "measurement": "humidity",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"outdoor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Accumulative count of alarm events",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_alarms",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature_alarms\" and\r\n    r._field == \"temperature_difference\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: true)\r\n  |> yield(name: \"count\")",
     "select": [
      [
       { "params": [ "temperature_difference" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Actual temperature with Alarm",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)\r\n  |> yield(name: \"Temperatura normale\")\r\n"
    },
    {
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"outdoor\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "alarms = from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"temperature_alarms\")\r\n  |> map(fn: (r) => ({ r with _value: 1 }))\r\n  |> aggregateWindow(every: 30s, fn: sum, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n\r\ntemperature = from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n\r\njoin(\r\n  tables: {t: temperature, a: alarms},\r\n  on: [\"_time\"]\r\n)\r\n|> map(fn: (r) => ({\r\n  _time: r._time,\r\n  _value: if r._value_a > 0 then r._value_t else float(v: 0),\r\n  _field: \"value\",\r\n  _measurement: \"temperature\"\r\n}))\r\n|> yield(name: \"Temperatura con allarme\")\r\n"
    }
   ]
  },
  {
   "title": "1min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature_predictions\" and\r\n    r._field == \"predicted_temperature\" and\r\n    r.forecast_horizon == \"1min\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "1min" }
     ]
    }
   ]
  },
  {
   "title": "10min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature_predictions\" and\r\n    r._field == \"predicted_temperature\" and\r\n    r.forecast_horizon == \"10min\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "10min" }
     ]
    }
   ]
  },
  {
   "title": "20min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature_predictions\" and\r\n    r._field == \"predicted_temperature\" and\r\n    r.forecast_horizon == \"20min\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "20min" }
     ]
    }
   ]
  },
  {
   "title": "30min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature\" and\r\n    r._field == \"value\" and\r\n    r.location == \"indoor\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"temperature_predictions\" and\r\n    r._field == \"predicted_temperature\" and\r\n    r.forecast_horizon == \"30min\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "30min" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "latency",
     "query": "from(bucket: \"ProgettoIot\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"latency\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}