{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "measurement": "temperature",
     "query": "SELECT \"value\" FROM \"temperature\" WHERE (\"location\"::tag = 'indoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "measurement": "humidity",
     "query": "SELECT \"value\" FROM \"humidity\" WHERE (\"location\"::tag = 'indoor') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "outdoor" }
     ]
    }
   ]
  },
  {
   "title": "Accumulative count of alarm events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature_alarms",
     "select": [
      [
       { "params": [ "temperature_difference" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "1min" }
     ]
    }
   ]
  },
  {
   "title": "10min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "10min" }
     ]
    }
   ]
  },
  {
   "title": "20min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "20min" }
     ]
    }
   ]
  },
  {
   "title": "30min prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Actual indoor temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location::tag", "operator": "=", "value": "indoor" }
     ]
    },
    {
     "alias": "Predicted indoor temperature",
     "measurement": "temperature_predictions",
     "select": [
      [
       { "params": [ "predicted_temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "forecast_horizon::tag", "operator": "=", "value": "30min" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}